### ISSUE TITLE
[QUESTION] How to login using session?

### ISSUE THREAD

**Issue by jmbits** [gave92/fbchat-sharp#10]

**Comment by jmbits** [comment]
SOLVED.
Using getsession() to save it and then setsession() when needed.
Amazing library! Any way to donate to keep this project alive?

**Comment by gave92** [comment]
Yes, either you use getsession() and setsession() or you can override the 3 methods of MessengerClient class `DeleteCookiesAsync`, `ReadCookiesFromDiskAsync`, `WriteCookiesToDiskAsync`. See [here](https://github.com/gave92/FMessenger/blob/c4144c6d9a62f7d24c613b0348dfc77ef06c6419/FMessenger/FMessenger.Shared.Global/Classes/FBClient.cs#L133) for an example of saving session cookies using SharpSerializer

I don't mind getting donations xD. You can do it [here](https://www.paypal.me/gave92).
