### ISSUE TITLE
Cannot log in

### ISSUE THREAD

**Issue by unipeg** [gave92/fbchat-sharp#11]
I have problems doing login. I do type the correct username/password, but still login is not succesful - boolean from DoLogin is false and no details seem available?
I have an old NodeJS application using facebook-chat-api and with this I can login.

I'm using this under dotnet core (2.1).

Any ideas?

**Comment by unipeg** [comment]
I've just compiled and verified that the example project of the solution runs fine with no errors. That project targets .NET Framework (4.5.1). What might be the problem with dotnet core?

**Comment by gave92** [comment]
Hello just tried the example project with .netcore 2.1 and it works for me. I added a netcore [example project](https://github.com/gave92/fbchat-sharp/tree/master/netcore). Please let me know if it works.

**Comment by unipeg** [comment]
I'll try it right away. My issue occured when I created a dotnet core console, and added the Gave.Libs.Fbchat package. Maybe you can reproduce this way too?

**Comment by gave92** [comment]
Ok the issue seems to be with the nuget package with uses outdated dependencies not compatible with netcore. I'll upload a new version soon. Thank you for pointing this out.
