### ISSUE TITLE
Any way to login as Page?

### ISSUE THREAD

**Issue by negapo** [gave92/fbchat-sharp#12]
Is there any way to retrieve data for a page (threads, messages, etc)?
I was looking for any options on the doLogin method to input the page ID but couldn't found anything.😊Thanks

By the way, amazing library, it's just very hard to find, once this becomes more visible in google im sure it will be huge.

**Comment by gave92** [comment]
Hi, you can:

- Find page ID by its name using "searchForPages"
- Get pages' info from ID using "fetchPageInfo"
- Get pages' messages using "FetchThreadMessages"
- Send messages to pages using "SendMessage"

**Comment by negapo** [comment]
Thanks gave92 for the fast reply.
If i understood correctly the steps you mention are for retrieving a conversation (thread) of my personal inbox with a page (i tested and in fact it works) but was looking for a way to retrieve threads of a page that i administer and not my personal account, is this possible? Thanks

**Comment by gave92** [comment]
Nope that is not supported. I think neither the original python library [fbchat](https://github.com/carpedm20/fbchat) nor [facebook-chat-api](https://github.com/Schmavery/facebook-chat-api) support this.
The official Facebook Api may do it though.

**Comment by negapo** [comment]
Thanks gave92. I think you are right and the fbchat doesn't support it, the facebook-chat-api does:

> Do you support sending messages as a page?
Yes, set the pageID option on login (this doesn't work if you set it using api.setOptions, it affects the login process).
login(credentials, {pageID: "000000000000000"}, (err, api) => { … }
> 
Im thinking in diving into your library and trying to implement this but i wanted your opinion, do you think this is doable? Thanks

**Comment by gave92** [comment]
Yes if they can do it, we can as well. fbchat-sharp is based on fbchat which is (loosely) based on facebook-chat-api. BTW I suggest you verify first that facebook-chat-api currently works for pages (which I'm not sure)
