### ISSUE TITLE
Facebook lock account

### ISSUE THREAD

**Issue by brianlogos** [gave92/fbchat-sharp#13]
Whenever I try to write a chat message facebook locks my account and forces me to change my password. With this great app my code is simple:

   MessengerClient client = new FBClient_Simple();
   var result = client.DoLogin(Email, Password).Result;
   var group = client.searchForGroups(Group).Result;
   var msg_uid = client.SendMessage(Message, group[0].uid, ThreadType.GROUP).Result;
   r = client.DoLogout().Result;

Does anyone else have this problem? Is there a workaround?

**Comment by jmbits** [comment]
I worked with this a while ago, and I remember having the same issue. I think it happens because you login every time you need to send a message. I fixed it by login in once, and saving the session. Next time, instead of login in again, just retrieve the session. I hope this helps.

**Comment by brianlogos** [comment]
Thanks very much! - I've changed the code to use cookie sessions so it does not need to login or out. I'll see how it goes and post any issues.
