### ISSUE TITLE
Account become untrusted really fast

### ISSUE THREAD

**Issue by EasyHax** [gave92/fbchat-sharp#17]
This error message happend from Facebook.

"We want to make sure your account is secure
We have recently noticed an unusual activity on your account. We have disconnected you for your safety and that of other users.
To re-access your account, we will guide you through a few steps."

I read it might be cause of creating too much session, so I used this code:

            `bool islogged = false;
            ConstVars.client = new FBClient_Cookies();
            var client = new FBClient_Cookies();
            islogged =  await ConstVars.client.TryLogin();
            if (islogged)
            {
                Console.WriteLine("got last session.");
            }
            else
            {
                Console.WriteLine("new session.");
                await ConstVars.client.doLogin("mail", "pass", 1);
            }
            await ConstVars.client.WriteCookiesAsync();`

It always returns "new session".
Any idea about how to process ?

**Comment by gave92** [comment]
Yes account becoming unteasted can be related to creating new sessions frequently.
If you execute the code in debug mode in visual studio, you should get some debug ouput when calling TryLogin()
Also check whether the cookies are saved, in the AppData/Local/FBCHAT folder

**Comment by EasyHax** [comment]
Thanks for answearing that fast first.
I tried debug the method, but everything seems ok.
I checked the cookies.dat and here is the content ->
`RootÎSystem.Collections.Generic.List`1[[System.Net.Cookie, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=#################\System.Net.Cookie, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=#################Capacity      Comment  
CommentUri HttpOnly Discard  Domain 
.facebook.com`
Is there a problem while writing the cookies ?
Thanks in advance.

**Comment by gave92** [comment]
Please try to delete the cookies file, verify you can login through facebook website and login again using the provided example (fbchat-sharp/examples)

**Comment by EasyHax** [comment]
I deleted the cookies file, checked I can login trough facebook properly, logged in using the exact same example, the "Message test" worked well. But TryLogin() always fails.
Here is the cookies the example created me - `RootÎSystem.Collections.Generic.List`1[[System.Net.Cookie, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089]], mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken="the _token_key"\System.Net.Cookie, System, Version=4.0.0.0, Culture=neutral, PublicKeyToken="the_token_key"Capacity      Comment  
CommentUri HttpOnly Discard  Domain 
.facebook.com`
Thanks again.

**Comment by gave92** [comment]
OK thank you unfortunately I'm not able to reproduce this behavior and that cookie file appears incomplete (should be 2-3KB in size). I'll think more on this

**Comment by EasyHax** [comment]
Thanks for the support ! It's appreciable. Hope I'll find a way to fix it.
