### ISSUE TITLE
Unable to Login Client.DoLogin always returns false

### ISSUE THREAD

**Issue by skmagiik** [gave92/fbchat-sharp#18]
Facebook provides me a notification on attempt to login:
           We noticed an unusual login from a device or location you don't usually use. Was this you?
I can select yes and also ask it to remember the browser but next login attempts also fail.
I have confirmed the username and password by typing it in manually again to login to facebook.
DoLogin returns false no matter the situation.

           // Instantiate FBClient
            FBClient client = new FBClient();
          
           // Login with username and password
           var logged_in = await client.DoLogin("username", "password");

**Comment by gave92** [comment]
Hello thanks for the report. When DoLogin returns false it should also print to console a message like "Login failed. Check email/password. (Failed on url: ...)". can you provide me that error message?

**Comment by PoLaKoSz** [comment]
@skmagiik When You login do you use custom implementation or the WPF/.NET Core sample app?

**Comment by skmagiik** [comment]
I was attempting to use the code directly from the core sample app within a
console application.

**Comment by PoLaKoSz** [comment]
Sorry my English not the best this is why i asking this:
Did You tried logging in with the `examples/netcore` app **without** any modification?

**Comment by gave92** [comment]
@skmagiik I just posted an updated version of the library see [here](https://github.com/gave92/fbchat-sharp/releases/tag/0.2.9). Let me know if it solves your problem!
