### ISSUE TITLE
How can i check if friend is online to start chat!!!

### ISSUE THREAD

**Issue by wayfaredark** [gave92/fbchat-sharp#19]
I want to perform a validation before list all my contacts and check which of my contacts are currently online.

**Comment by gave92** [comment]
at this moment contacts online status is not available, but I'm working on it.

**Comment by wayfaredark** [comment]
Thanks.

**Comment by gave92** [comment]
Hello in version [0.2.9](https://github.com/gave92/fbchat-sharp/releases/tag/0.2.9) I added a new "fetchActiveUsers()" method that gives you the list of ids of the currently active users.
