### ISSUE TITLE
Cannot send messages to groups 

### ISSUE THREAD

**Issue by JonasUliana** [gave92/fbchat-sharp#2]
Error information:

```
{"Error when sending request: Got InternalServerError response"}
```

**Comment by gave92** [comment]
Hi, sending message to groups works for me.
When you call the "SendMessage" function for a group be sure to set the 3rd optional argument (thread_type) to "ThreadType.GROUP"
`var msg_id = await App.ClientInstance.SendMessage("message", "1500224085", ThreadType.GROUP);`
