### ISSUE TITLE
Facebook locks the account although I use Cookie sessions

### ISSUE THREAD

**Issue by ahmed605** [gave92/fbchat-sharp#24]
Facebook locks my account although I use Cookie sessions to login every time the app opened with  `Client.TryLogin()` method

**Comment by gave92** [comment]
I've received reports of Facebook locking the account but I could not track down the problem. If you're willing, nabling 2 factor authentication on your FB account seems to be of help.

**Comment by ahmed605** [comment]
the login works with the both ways after re-unlocking my FB account. I mean is there a way to use client without re-logging every time I open the app

**Comment by gave92** [comment]
Client.TryLogin() should do just that, no need to use username and pw after the first time (just don't call Client.DoLogout()). It should be ok calling Client.TryLogin() every time you open your app.

**Comment by ahmed605** [comment]
I'm already using Client.TryLogin()

**Comment by gave92** [comment]
And what happens? The login fails? With what error?

**Comment by ahmed605** [comment]
after logging many times with Client.TryLogin() (to test code changes) the facebook locked the account then the Client.TryLogin() returns false but after re-unlocking the account the tryLogin() works but I mean is there a way to use client without re-logging every time I open the app

**Comment by gave92** [comment]
OK you may try adding this function to your `MessengerClient`. This just loads the cookies without connecting to https://www.facebook.com/login to check is they're valid.

```c#
public new async Task<bool> TryLogin()
{
    try
    {
        var session_cookies = await this.ReadCookiesFromDiskAsync();
        await base.setSession(session_cookies);
        return true;
    }
    catch (Exception ex)
    {
        this.Log(ex.ToString());
        return false;
    }
}
```

**Comment by ahmed605** [comment]
Thx I got it
