### ISSUE TITLE
FB_User.color always returns null

### ISSUE THREAD

**Issue by ahmed605** [gave92/fbchat-sharp#25]
FB_User.color always returns null and I think it should be `ThreadColor` not `String`and if it should be a String then it must returns the color hex code

**Comment by gave92** [comment]
Commit 41fcfe772b9a84c0811cabc741bd2527da2ed010 should fix this. FB_User.color is string, ThreadColor is only to provide default colors. You can change a thread color using client.changeThreadColor("#ffbb99", THREAD_ID)

**Comment by ahmed605** [comment]
Thx the problem solved. but I found many bugs in this lib some I can fix by myself and some not so can I create many issues and pull requests for that bugs?

**Comment by gave92** [comment]
Feel to open pull requests!
