### ISSUE TITLE
doLogin() throws System.TypeLoadException

### ISSUE THREAD

**Issue by apepenkov** [gave92/fbchat-sharp#26]
```
Client client = new Client();
await client.doLogin(login, password);
```
throws error
```
Could not load "AngleSharp.Parser.Html.HtmlParser" from "AngleSharp, Version=0.13.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea".
 StackTrace:    in fbchat_sharp.API.Client.<_login>d__41.MoveNext()
   in System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.Start[TStateMachine](TStateMachine& stateMachine)
   in fbchat_sharp.API.Client._login()
   in fbchat_sharp.API.Client.<doLogin>d__46.MoveNext()
---
in System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   in System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   in socialPost.MainWindow.<DoFacebookMessendgerAsync>d__91.MoveNext()
Data: System.Collections.ListDictionaryInternal, Source: fbchat-sharp

```

in fbchat (python) same loggining info passes fine

**Comment by ahmed605** [comment]
try using client.DoLogin() not client.doLogin()

**Comment by apepenkov** [comment]
![image](https://user-images.githubusercontent.com/39992738/64911307-80bc5280-d728-11e9-9e8e-e631535d919e.png)
not found

**Comment by apepenkov** [comment]
I am using AngleSharp 0.13 and FbChat itself 0.2.8

**Comment by apepenkov** [comment]
looks like i have to use MessengerClient instead of Client?

**Comment by apepenkov** [comment]
![image](https://user-images.githubusercontent.com/39992738/64911335-fd4f3100-d728-11e9-8c4a-220a89db6316.png)
nope, Could not create abstract

**Comment by ahmed605** [comment]
this version of FbChat is old use the dev version with AngleSharp 0.9.11, Microsoft.NETCore.Portable.Compatibility 1.0.1, NETStandard.Library 1.6.1, Newtonsoft.Json 11.0.2 and System.ComponentModel.Annotations 4.5.0
[fbchat-dev.zip](https://github.com/gave92/fbchat-sharp/files/3612947/fbchat-dev.zip)

**Comment by apepenkov** [comment]
Why don't u add new to NuGet?.. OK

**Comment by apepenkov** [comment]
Why don't u add it to nuGet? that's the last version there...
![image](https://user-images.githubusercontent.com/39992738/64911391-e65d0e80-d729-11e9-8b1b-20b9ced40f21.png)

**Comment by ahmed605** [comment]
I don't have rights (access) to update the lib on Nuget

**Comment by apepenkov** [comment]
Allright, thx

**Comment by apepenkov** [comment]
Allright, i installed everything as u told.
![image](https://user-images.githubusercontent.com/39992738/64911588-756b2600-d72c-11e9-8367-b7fd1a78500f.png)
only login() exists now, and it throws
```
Error: Message: Could not load "AngleSharp.Parser.Html.HtmlParser" from "AngleSharp, Version=0.13.0.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea"., 
```
even if i have  AngleSharp 0.9.11

**Comment by apepenkov** [comment]
forgot to re-open, comment above is problem

**Comment by ahmed605** [comment]
what's the client type?

**Comment by ahmed605** [comment]
change the `AngleSharp` version in the `*.csproj` and `project.json`

**Comment by apepenkov** [comment]
fbchat_sharp.API.Client

**Comment by ahmed605** [comment]
what's your platform?

**Comment by apepenkov** [comment]
Windows 10

**Comment by apepenkov** [comment]
![image](https://user-images.githubusercontent.com/39992738/64912391-21197380-d737-11e9-8a2f-02a495d7a0e0.png)
changing that in app.config solved that problem. But i've got error while sending message System.ArgumentNullException
I'll re-run and get more nifo about it

**Comment by ahmed605** [comment]
I mean UWP/WinForms/WPF/Windows Phone/.Net Core/.Net Standard?

**Comment by apepenkov** [comment]
WPF

**Comment by apepenkov** [comment]
So the error is
```
The value cannot be undefined
```
```
parametr content 
StackTrace:    in System.Net.Http.StreamContent..ctor(Stream content, Int32 bufferSize)
   in fbchat_sharp.API.State.<_postFile>d__25`1.MoveNext()
```
my sending message code:
```
string msg_uid;
FB_Message message = new FB_Message(text: postBody);
msg_uid = await client.send(message, user);
```

**Comment by ahmed605** [comment]
```cs
FBClient client = new FBClient();
```

```cs
var logged_in = await client.DoLogin(email, password);

// Check login was successful
if (logged_in)
{
}
```
```cs
public class FBClient : MessengerClient
{
    protected override async Task DeleteCookiesAsync()
    {
        await Task.Yield();
    }    
        
    protected override async Task<Dictionary<string, List<Cookie>>> ReadCookiesFromDiskAsync()
    {
        await Task.Yield();
        return null;
    }

    protected override async Task WriteCookiesToDiskAsync(Dictionary<string, List<Cookie>> cookieJar)
    {
        await Task.Yield();
    }
}
```

**Comment by apepenkov** [comment]
Works, Thanks for patience
