### ISSUE TITLE
Cannot login in when using release mode in UWP app

### ISSUE THREAD

**Issue by ahmed605** [gave92/fbchat-sharp#28]
Cannot login in when using release mode in UWP app (in Debug it works) and shows this error
![rel](https://user-images.githubusercontent.com/34550324/65781688-587f1b80-e14c-11e9-894e-c2b9ae718ae1.PNG)

**Comment by gave92** [comment]
Could you confirm that the problem is not actually "Release mode" but the option "Compile using .net native toolchain" under Debug tab in project properties?

**Comment by ahmed605** [comment]
Mostly the problem is from .net native toochain but I can't publish the app on store without this toochain but I can't test it now because I'm not home right now

**Comment by gave92** [comment]
Guess reflection has issues when using .net native. I'll see if I can do without.

**Comment by ahmed605** [comment]
If you used Reflection it must be .net native problem every UWP app that I created had this issue before because I used Reflection so you you will take a lot of time converting  Reflection Dynamic code to Static/Normal code

**Comment by gave92** [comment]
Please let me know if commit 5ff948f5a7f5c70df2ab02e69c4e04cc10c8296a fixes the problem.

**Comment by ahmed605** [comment]
I'm not on PC right now but I can see you disabled .net native toochain in UWP example so does it can work without disabling it

**Comment by gave92** [comment]
That line refers to Debug configuration

**Comment by ahmed605** [comment]
As always worked perfectly thank you very much!
