### ISSUE TITLE
onMessage not working

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#29]
Hello i using this app for logging my messages but now not working onMessage on netcore logging is without problem but onmessage not works :(

**Comment by k4r3l01** [comment]
and its because fbmsgr migrated to MQTT over websocket and in this repo is solution but its in python and not C# :( https://github.com/tulir/fbchat-asyncio

**Comment by gave92** [comment]
hello, I'm working on adding MQTT support. You may try out the latest commit 866a08806db0c9bd0f842893f2129efb251e189f in the develop branch.

**Comment by k4r3l01** [comment]
thanks with develop branch its working
