### ISSUE TITLE
Error in fetchThreadList

### ISSUE THREAD

**Issue by VideoAppsNet** [gave92/fbchat-sharp#31]
I get this error = Unknown thread type: MARKETPLACE. I can see from your source code that there is no marketplace. Maybe Im doing something wrong? Im on Windows 10 UWP. Thanks.

**Comment by VideoAppsNet** [comment]
fbchat_sharp.API.FBchatException: 'Unknown thread type: MARKETPLACE'

This exception was originally thrown at this call stack:
fbchat_sharp.API.Client.fetchThreadList(int, string, string)
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(System.Threading.Tasks.Task)
System.Runtime.CompilerServices.TaskAwaiter<TResult>.GetResult()

**Comment by gave92** [comment]
Hello thanks for the feedback. Is the above the full stacktrace? The error you mention should not happen on a call to "fetchThreadList" but only when calling methods like "sendMessage" or similar.

**Comment by VideoAppsNet** [comment]
Yes that is the full stack trace. I get this error each time I try to fetchThreadList. Im testing on my Desktop PC, running the newest Windows 10 1909. I searched around in your source code and I have not found marketplace thread type. Maybe this is the issue? Marketplace is not set in your source code? Steps to reproduce is to login to facebook from the app, then run fetchThreadList to fill in data for my app. Error happens each time.

**Comment by gave92** [comment]
You may try to use the latest commit 105409123851b1d2400e937d94b75118e048bc4a in the develop branch. Marketplace threads are not currently supported, the commit only avoids to raise an error for those. Feel free to reopen if you still experience issues.

**Comment by VideoAppsNet** [comment]
Sorry im new to git hub. How can I use this commit in Visual Studio nuget? Thanks.

**Comment by ahmed605** [comment]
@VideoAppsNet you cannot use this commit with Nuget you need do download 'dev' branch source and build it yourself because it's not published yet in Nuget
