### ISSUE TITLE
Markalive problem

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#32]
Hello please i have problem with markalive i have markalive falsr but iam permanently active on fb by my bot so markalive not working i think

**Comment by gave92** [comment]
Hello this appears to be due to a change on FB side and also the original python [fbchat](https://github.com/carpedm20/fbchat) library has the same issue. I don't think I can solve this.

**Comment by gave92** [comment]
Hello please give the latest develop commit d2ef9a9581232f675fa9dcb6aac5cf39f3cb643b a try. You should be able to send/receive messages without appearing online (you will only appear online for a few minutes after logging in). Use `await Client.StartListening(false);`

**Comment by k4r3l01** [comment]
thanks i will try

**Comment by k4r3l01** [comment]
Sot its working thanks for your great work
