### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#33]
Hello please its will be possible to capture pictures,videos and voice messages  i nean attachmebts and automaticaly download to pc? if yes how many thanks in advance for your answer sinceresly K4r3l01

**Comment by ahmed605** [comment]
@k4r3l01 yes you can!
I have done that before in my UWP app!
All you need is getting the attachment url (this library allows you to do this) and then you have two options:
- opening the URL as URI so it will open the browser and start downloading the file!
- creating your own download task to save/download the file from the app directly!
