### ISSUE TITLE
2 Factor Authentication Not Working with SMS

### ISSUE THREAD

**Issue by VideoAppsNet** [gave92/fbchat-sharp#34]
Iam able to login with with no authentication and everything is working fine. I turned on 2 step authentication and now its not working. Im using this sample project with no code changes. The Inputbox comes up asking to enter my code but I never get the code to my phone. If I login from the browser it works fine. I get the sms and I can login. But for the app it does not work. I tried both uwp and wpf. The only thing that happens is that Facebook sees a login request and blocks that request. There is no sms being sent. It only gets blocked. Seems like sms 2 step is not being initiated from the app. If i use anything else such as browser or Facebook Messenger I get the sms code and I can login. Please can you help with this? Everything else is working great just this one last thing. Thank you. Here is the error I get from facebook when I check from the browser === 

Review Recent Login
Someone recently tried to log into your account from an unrecognized computer or mobile browser. Because you set up two-factor authentication, your account is temporarily locked. Please complete the following steps to regain access to your account.

**Comment by gave92** [comment]
2 step authentication works ok for me. I don't receive the code via SMS, instead I get it from the Google Authenticator app. Could you check if using the app instead of the SMS works for you?

**Comment by VideoAppsNet** [comment]
I have tested it with authentication app and it works. Thats good. Then I immediately switched to sms authentication and I never get any code to my phone. If i login with my browser I get the code right away but not within the app. This is a huge problem as anyone with sms authentication can never login. Thanks.

**Comment by gave92** [comment]
Hello I tried on my test account and 2FA with SMS works fine for me (code is received right away). Verified with the .NET core and WPF examples.

**Comment by VideoAppsNet** [comment]
Thanks. I got it to work. Seems that my old facebook account was failing to send me an sms for verification. I created a new facebook account for testing and it works on that account. Seems something is wrong with old account as receiving verification code always failed. Worked on desktop or phone but not with fbchat-sharp. Anyway thank you.
