### ISSUE TITLE
Building for UWP Windows Store = Error

### ISSUE THREAD

**Issue by VideoAppsNet** [gave92/fbchat-sharp#35]
Hello everyone. I have another error I hope you can help to fix. When building this app for UWP I get a certification error. Im building only for x64 in release mode. Here is the error. 
--------------------
Binary analyzer
Error Found: The binary analyzer test detected the following errors:
File clrjit.dll has failed the AppContainerCheck check.
Impact if not fixed: If the app doesn’t use the available Windows protections, it can increase the vulnerability of the customer's computer to malware.
How to fix: Apply the required linker options - SAFESEH, DYNAMICBASE, NXCOMPAT, and APPCONTAINER - when you link the app. See links below for more information:
--------------------

This is when I build in release mode and run the certification program. App works fine when I deploy in debug and release on my pc. But when I run the certification on the release package of this app it fails. Also keep in mind that I did not add any nuget packages or other librarys. This is strikly only the the code from this github. Thanks.

**Comment by VideoAppsNet** [comment]
I was able to solve this issue by removing nuget package .net core comparability from the fbchat-sharp portable project. Now it passed all UWP certifications.

**Comment by gave92** [comment]
I included your solution in the latest release 0.3.2. Thanks for the help.
