### ISSUE TITLE
Error StartListening with .Net Standard 4.7

### ISSUE THREAD

**Issue by gx-ribeiro** [gave92/fbchat-sharp#36]
The included example works perfectly, but when I try to implement it in my project, an error is triggered "The header 'Referer' must be modified with the appropriate property or method".

The error is occurring at line 3363 of the Client.cs file
![Error1](https://user-images.githubusercontent.com/60554021/73598574-e616b180-4518-11ea-9e85-06abb422dbff.jpg)

The exception is fired at the caller.
![Error2](https://user-images.githubusercontent.com/60554021/73598584-fb8bdb80-4518-11ea-8a3a-e51c4d533f34.jpg)

This error is really expected, as some Headers cannot be specified, as documented in HttpWebRequest.Headers.
But I did not find in MQTTnet.Client a way to specify the Referer directly in a property, in this way, I believe that the error is not in your code, but in MQTTnet.

The solution found was to add remark in 3 lines of code, as below and everything works fine.
![Error3](https://user-images.githubusercontent.com/60554021/73598588-11999c00-4519-11ea-95ce-1a7c0b7cc9d4.jpg)

I don't know why it works well with Net Core, because I didn't evaluate the MQTTnet code, but I believe it is a good idea to report the error to them and request a parse in the header properties and add the restricted headers in their corresponding properties.

Thank you very much and great work.

**Comment by gave92** [comment]
Hello assuming your project is targeting .Net Framework 4.7 please have a look to [this file](https://github.com/gave92/fbchat-sharp/blob/master/examples/wpfapp/Helpers/WtfWpf.cs) included in the WPF example. This is why it works in the example :)

**Comment by gx-ribeiro** [comment]
Thank you very much for your prompt attention. I will check this out tonight and answer as soon as possible.

**Comment by gx-ribeiro** [comment]
It worked like a charm.
I put it in my FBClient.cs, like this:

```
using fbchat_sharp.API;
using Newtonsoft.Json;

namespace ExFacebook
{
    public class FBClient : MessengerClient
    {

        public static string Instance = "";
        public FBClient(string currentInstance)
        {
            Instance = currentInstance;
            this.Set2FACallback(get2FACode);
            UnsetRestrictedHeaders();
        }
   ...
   ...
   ...
```

Thanks for your response and your component.
