### ISSUE TITLE
Multiples connected accounts at same time

### ISSUE THREAD

**Issue by gx-ribeiro** [gave92/fbchat-sharp#37]
I need to run multiple instances, receive and send messages on all of them at the same time.
I am able to easily send messages through the correct account, but when receiving messages, two things happen:
1) The "onMessage" event is triggered once for each account logged in, for example, if I have an account logged in, the event is triggered once. If I have 3 accounts, the same message triggers the event 3 times, each time with the same message.
2) I cannot identify the account that received the message. In all parameters of the event "onMessage", only the data of the sender is informed and at no time the recipient.

I tried in three ways and always with the same result:

- Instantiating a class multiple times:
myClass runInctance1 = new myClass();
myClass1.Login();
myClass runInctance2 = new myClass();
myClass2.Login();

- With Thread:
Thread runInstance = new Thread (new ThreadStart (myClass.Login));
runningInstance.Start ();

-With ThreadPool:
ThreadPool.QueueUserWorkItem (myClass.Login);

I believe I am doing something wrong, as I am not an expert in C# and your routine is very well done and working very well.
One more thing. I'm creating a .Net Standard 4.7 library (DLL) and haven't tested it with Core or any other way.

Thanks in advance.

**Comment by gave92** [comment]
Thanks for reporting this. This is a scenario I've never tested, I'll try as soon as I can.

**Comment by gave92** [comment]
`onMessage()` callback has a "author_id" parameter. This will be the ID of the sender. To check which account has sent the message you can compare "author_id" with the ID from `client.GetUserUid()`.

**Comment by gave92** [comment]
Ok I've tested the multiple accounts scenario. The code I used is [here](https://gist.github.com/gave92/9fe8ddb7cda2c3bba5d8382e1968eb76).
I create 3 accounts and then send a message from "account1" to "account2". The `onMessage()` is called only on "account1" and "account2". You can check if an account is the sender or the recipient by comparing the "author_id" parameter with the account ID (`clientX.GetUserUid()`)

**Comment by gx-ribeiro** [comment]
Eu criei um exemplo completo utilizando seu código anexado como base. Infelizmente o mesmo problema permanece ocorrendo e não sei o que pode ser.
Anexei o projeto completo e para testar você só precisa informar o e-mail da conta e senha.

[FBTest.zip](https://github.com/gave92/fbchat-sharp/files/4150665/FBTest.zip)

**Comment by gx-ribeiro** [comment]
Eu criei um exemplo completo utilizando seu código anexado como base. Infelizmente o mesmo problema permanece ocorrendo e não sei o que pode ser.
Anexei o projeto completo e para testar você só precisa informar o e-mail da conta e senha.
237/5000
I created a complete example using your attached code as a base. Unfortunately the same problem continues to occur and I don't know what it can be.
I attached the complete project and to test you just need to inform the account email and password.

[FBTest.zip](https://github.com/gave92/fbchat-sharp/files/4150677/FBTest.zip)

**Comment by gx-ribeiro** [comment]
I created a complete example using your attached code as a base. Unfortunately the same problem continues to occur and I don't know what it can be.
I attached the complete project and to test you just need to inform the account email and password.

[FBTest.zip](https://github.com/gave92/fbchat-sharp/files/4150678/FBTest.zip)

**Comment by gx-ribeiro** [comment]
Still testing, I understood what is happening. The event is firing if both accounts are logged. If a third account, which is not logged in sends a message, everything works correctly.
But, if a logged in account sends to another account logged into the component, the onMessage event fires for both users.
I did a workarround here, adding the following code:

```
        protected override async Task onMessage(string mid = null, string author_id = null, string message = null, FB_Message message_object = null, string thread_id = null, ThreadType? thread_type = null, long ts = 0, JToken metadata = null, JToken msg = null)
        {
            if (message_object.author == this.GetUserUid() && !message_object.is_from_me)
            {
                Console.WriteLine("Ignoring this message");
            } else
            {
                Console.WriteLine(string.Format("Got new message from {0} to {1}: {2}", author_id, this.GetUserUid(), message));
                await Task.Yield();
            }
        }
```

**Comment by gave92** [comment]
Do not use the "is_from_me" field. It is not filled and always false I think. The following should be enough.

```c#
protected override async Task onMessage(string mid = null, string author_id = null, string message = null, FB_Message message_object = null, string thread_id = null, ThreadType? thread_type = null, long ts = 0, JToken metadata = null, JToken msg = null)
        {
            if (message_object.author == this.GetUserUid())
            {
                Console.WriteLine("Ignoring this message");
            } else
            {
                Console.WriteLine(string.Format("Got new message from {0} to {1}: {2}", author_id, this.GetUserUid(), message));
                await Task.Yield();
            }
        }
```
