### ISSUE TITLE
Exception fbchat_sharp.API.FBchatFacebookError

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#38]
Hello i giving exception more info in screen

![exception](https://user-images.githubusercontent.com/6354127/76699460-eeccdc80-66ad-11ea-9a47-25e616c7077a.png)

**Comment by gave92** [comment]
Thanks for reporting this. This is a change on the Facebook side.
Please try again with the latest commit 2c11386f381ae89d4534a3ceb4e95b8e8390e8b0
