### ISSUE TITLE
again exception :(

### ISSUE THREAD

**Issue by k4r3l01** [gave92/fbchat-sharp#42]
Hello i have again exception
Exception thrown: 'fbchat_sharp.API.FBchatPleaseRefresh' in fbchat-sharp.dll
Refreshing state and resending request

after latest update its worked for few days but today its back :(

**Comment by gave92** [comment]
The latest commit in the *develop* branch will work if you don't have 2FA enabled.

**Comment by k4r3l01** [comment]
its seems to be working but its completely edited from v1 version because i need to get author name of message and in this i dont know how.
and you have small bug in netcore basic_usage.cs on line 21 in this if must be == not !=

**Comment by gave92** [comment]
Sorry but this won't be backported on v1.
To fetch a user name from message (FB_Message):
```cs
var sender = (await client.fetchThreadInfo(new List<string>() { message.author })).Single().Value as FB_User;
Console.WriteLine(sender.name);
```

**Comment by k4r3l01** [comment]
Please i have last question how to get thread_id in message event thanks in advance for your answer
