### ISSUE TITLE
Error FetchThreadMessages With Big Stikers And Like Stiker in Facebook Chat

### ISSUE THREAD

**Issue by dante1989** [gave92/fbchat-sharp#5]
When I call Function FetchThreadMessages(thread_id:=chat_id, limit:=20) to get 20 Messages
It work very well

But if 20 Messages have Big Stikers or Like Stiker like this: https://drive.google.com/file/d/1ipHi9_AjuSvqzZPmaJUSb6kA5bOeJv_D/view?usp=sharing

And I get no Messages. Nothing Happen

Could you help me to fix that Problem?
Thank You So Much :D

**Comment by gave92** [comment]
Tested reading messages with stickers.. works fine for me. Please check with the latest version, and feel free to reopen the issue if the problem still persists.
