### ISSUE TITLE
Verbosity Setting

### ISSUE THREAD

**Issue by NobleAscent** [gave92/fbchat-sharp#7]
I have been trying to login serveral times however I get nothing apart from a simple false boolean. Is there any way to debug why the login is failing? I have tried to use the example project as well but it also fails to login. I have checked email and password multiple times.
Regards

**Comment by gave92** [comment]
[https://tr.cloudmagic.com/h/v6/emailtag/tag/2.0/1531298381/61a1513d7a3dc9bf58f178908b474fbf/7/31d11b72606f2b78eea920618ba8430a/0f1e7c561b6468969dbee0d7a92ed423/9efab2399c7c560b34de477b9aa0a465/newton.gif]

When running the example project in debug mode, it should print the error to the console.

via Newton Mail<https://cloudmagic.com/k/d/mailapp?ct=pa&cv=9.8.320&pv=7.0&source=email_footer_2>
On Wed, Jul 11, 2018 at 9:32am, NobleAscent <notifications@github.com<mailto:notifications@github.com>> wrote:


I have been trying to login serveral times however I get nothing apart from a simple false boolean. Is there any way to debug why the login is failing? I have tried to use the example project as well but it also fails to login. I have checked email and password multiple times.
Regards

**Comment by 6a61756d** [comment]
On my first try, I got the same issue. When I accessed the account using a web browser, Facebook disabled the account due to some kind of "malicious log-in". I just verified that it was me and it cleared the issue on my end.

**Comment by NobleAscent** [comment]
I fixed the issue by updating the nuget packages for both the projects to the latest version. Gave is there any way to use App Passwords with this project?

**Comment by shinshin197** [comment]
Hello gave92. i trying using fbchat-sharp to login facebook but this don't working. I saw your example but i don't understand.  Please tell to me  how to login facebook using fbchat-sharp? thank you so much.!

**Comment by gave92** [comment]
@NobleAscent glad to hear it works. There is currently no support for 2FA. Never tested with App Passwords though, you just can try to `client.doLogin("usarname","AppPassword");`

**Comment by NobleAscent** [comment]
@gave92 The library does not work with App Passwords. It throws the Error Check Login exception. :(

**Comment by gave92** [comment]
@NobleAscent thank you for the feedback. Nuget package version 0.2.4 has now support for 2FA. App Password does not work but you can just provide the 2FA code you get from SMS/Authenticator app/...
